# Dependencies
markdown:         redcarpet
highlighter:      rouge
gems: [jekyll-paginate]

# Permalinks
permalink:        pretty


# Setup
title:            Kaushik SK
tagline:          'Blog'
description:      'Exploratory eyes into data, computer science and beyond.'
baseurl:          /

author:
  name:           'Kaushik S Kalmady'
  url:            https://github.com/kaushiksk

paginate:         5

# Custom vars
version:          2.1.0

#github:
#  repo:           https://github.com/poole/hyde
