# Dependencies
markdown:         kramdown
highlighter:      rouge
plugins:          [jekyll-paginate]

# Permalinks
permalink:        pretty


# Setup
title:            Kaushik SK
tagline:          'Blog'
description:      'Musings and findings from all things learnt, built and explored.'
baseurl:          /

author:
  name:           'Kaushik S Kalmady'
  url:            https://github.com/kaushiksk

paginate:         1


